/*
Observability Service API

Testing MicrobatchesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_MicrobatchesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test MicrobatchesAPIService MicrobatchesEventsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.MicrobatchesAPI.MicrobatchesEventsGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MicrobatchesAPIService MicrobatchesMicrobatchIdDurationGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var microbatchId string

		resp, httpRes, err := apiClient.MicrobatchesAPI.MicrobatchesMicrobatchIdDurationGet(context.Background(), microbatchId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MicrobatchesAPIService MicrobatchesMicrobatchIdStatusGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var microbatchId string

		resp, httpRes, err := apiClient.MicrobatchesAPI.MicrobatchesMicrobatchIdStatusGet(context.Background(), microbatchId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
